### PR TITLE
Issue 68/prefered components order

### PR DESCRIPTION
**Pull request by naomijub**
Addressing https://github.com/rewin123/space_editor/issues/68
I know this is not the best solution, but it is a straight forward solution for this

### CODE REVIEW

**Comment by naomijub** [comment]
Also, sorry for the missing lints, they were missing because of the Rust 1.74 config

**Comment by naomijub** [comment]
The alternative I tried was this sort: https://github.com/naomijub/space_editor/blob/optional-sort/src/editor/ui/inspector/components_order.rs

https://github.com/naomijub/space_editor/blob/optional-sort/src/editor/ui/inspector/mod.rs#L152
https://github.com/naomijub/space_editor/blob/optional-sort/src/editor/ui/inspector/mod.rs#L40

But it fails miserably

**Comment by rewin123** [comment]
Thanks for the pull request!
I look a quick look at it. It seems that for small queues, such as a list of components, a simpler way of sorting and storing the weight of the component in the sort can be used. 
It is possible to allocate a separate storage of component sort priority
'''rust
pub compoent_sort_priority : HashMap<ComponentId, usize>
'''
Collect all data into the component information vector in the inspector 
'''rust
let mut components_id = Vec::new();
    for reg in registry.iter() {
        if let Some(c_id) = world.components().get_id(reg.type_id()) {
            let name = pretty_type_name::pretty_type_name_str(
                world.components().get_info(c_id).unwrap().name(),
            );
            let priority = some_storage.compoent_sort_priority.get(&c_id).unwrap_or_default()
            components_id.push((c_id, reg.type_id(), name, priority));
        }
    }
'''
and sort it as follows
'''rust
components_id.sort_by(|(.., name_a, priority_a), (.., name_b, priority_b)| {
   if priority_a < priority_b {
      Ordering::Greater
   } else if priority_a == priority_b {
      name_a.cmp(name_b)
   } else {
      Ordering::Less
   }
});
'''

What do you think?

**Comment by naomijub** [comment]
I figured another way, will open PR now

**Pull request closed without merging**
