### PR TITLE
[BRUTEFORCE] Fixes editor crash when using it as plugin

### PR DESCRIPTION
**Pull request by naomijub**
Addresses issue https://github.com/rewin123/space_editor/issues/191 

Creates necessary filesystem when using space_editor as plugin

obs: My initial idea was to store the content as svg and render the svgs with bevy, but bevy and third parties plugins dont support svg as image, so I kept the initial approach and created a file system based on that

### CODE REVIEW

**Comment by naomijub** [comment]
This is a less brute force solution for the problem. However, I seem to be messing the the scheduling of the components https://github.com/rewin123/space_editor/pull/201

**Comment by rewin123** [comment]
I tested on empty project. Had compilation error

image

**Comment by rewin123** [comment]
Looks that error reaises from moving from bevy_egui to bevy_egui_next. I think we need add to CI pipeline chack that space_editor compilates and runs as plugin

**Comment by naomijub** [comment]
This error is because of the patch, we need to add patch to cargo toml

**Comment by rewin123** [comment]
Editr was compiled after update rust version and add patch in Cargo. But I got infinity loading 

image

**Pull request closed without merging**
