### PR TITLE
Documentation first pass

### PR DESCRIPTION
**Pull request by naomijub**
Docs readme - https://github.com/rewin123/space_editor/blob/0fb0554ca3f7c0aed5eed6686c0550d305a8b5f6/docs/README.md

root readme - https://github.com/rewin123/space_editor/blob/0fb0554ca3f7c0aed5eed6686c0550d305a8b5f6/README.md

### CODE REVIEW

**Comment by naomijub** [comment]
@rewin123 fixed some broken examples

**Comment by naomijub** [comment]
https://github.com/rewin123/space_editor/issues/116

**Comment by naomijub** [comment]
This pr covers
- broken scenes
- documentation
- updated ui
- some function naming improvements

**Comment by rewin123** [comment]
Docs and main repo readmy looks good

**Pull request merged**
