### PR TITLE
Fix camera overlapping

### PR DESCRIPTION
**Pull request by rewin123**
#140 
image

### CODE REVIEW

**Comment by naomijub** [comment]
Was very excited to test this PR and found this issue:
Captura de Tela 2024-01-02 às 3 54 50 PM

To reproduce it I created the CameraView tab in the same node as GameView, then moved it to the inspector node. The Image didnt rescale the viewport

**Comment by rewin123** [comment]
image
Fixed, may be

**Comment by naomijub** [comment]
I got this: 
Captura de Tela 2024-01-02 às 4 53 47 PM

Maybe keep the height proportion with the tab width, like it was before?

**Comment by rewin123** [comment]
Ye. Cathed it:(

**Comment by rewin123** [comment]
Oh, problem was in system order. I think fixed

**Review by naomijub — COMMENTED** [review]
Vídeo sem título ‐ Feito com o Clipchamp

If I add the camera first, then the cube, I get the above error. Any ideas why? @rewin123 ?

**Comment by rewin123** [comment]
Hm. Well, I thought that problem was in system order

**Comment by rewin123** [comment]
May be need to move all camera logic into ui tab method

**Comment by naomijub** [comment]
> May be need to move all camera logic into ui tab method

I think I found the issue, but will take a couple of days for me to push

**Pull request merged**
