### PR TITLE
Simple terrain generation

### PR DESCRIPTION
**Pull request by naomijub**
# Procedural Terrain Mesh Generation
> This is hidden under an `experimental` feature

image

This uses perlin and opensimplex functions to generate terrain data such as Height, Temperature and Moisture.

Should we create a branch 0.4 and start working on that branch instead of main?

### CODE REVIEW

**Comment by rewin123** [comment]
Yeah, maybe. Then bug fixes can be added to the main for version 0.3 without delaying their appearance until 0.4.

**Comment by rewin123** [comment]
I use space_editor to create my space sandbox. So I can also invest in a terrane generator in the future too

**Comment by rewin123** [comment]
I finished code separation. Can you fix conflicts? Or I could do it tomorrow

**Comment by naomijub** [comment]
> I use space_editor to create my space sandbox. So I can also invest in a terrane generator in the future too

This is mostly a MVP version to start.

Will fix the issues

**Comment by rewin123** [comment]
Do you don't mind if the pull request is uploaded only after 0.3 is ready? Additionally, the land generation should definitely be in the modules folder, as it is definitely not the core of the editor. (I consider the core of the editor to be the functionality that is needed to interact with entity component values, quick access to entities, easy entity placement on a level or prefab, and everything that is needed to link optional modules).

**Comment by naomijub** [comment]
No problem, it gives me tive to improve it a bit

**Comment by Sandvoxel** [comment]
Also might want to add an example to the examples folder.

**Comment by rewin123** [comment]
It seems that the terrain generation library should also be consistent with the #94

**Comment by naomijub** [comment]
Closing due to conflicts

**Pull request closed without merging**
