### PR TITLE
Issue 159

### PR DESCRIPTION
**Pull request by ncomendant**
Current progress on issue #159. Currently only has `bevy::input::gamepad::GamepadEvent` registered, and even that cannot change most values from its defaults.

### CODE REVIEW

**Comment by rewin123** [comment]
Thanks for the PR. But I think writing wrappers is the hard way. I would suggest adding a method to log sending events that doesn't require a Default implementation. This can be done with manual registration of implementation default behaviour without wrapping

```rust
fn register_just_event<T : Event>(name : Stroig, create_default : Box<dyn FnMut() -> T>) {
//register creator function 
}
```

@ncomendant WDYT?

**Comment by ncomendant** [comment]
Yes, that would definitely be preferred. The PR is a very brittle solution and not ideal.

I think `Default` is not the issue, but currently events must implement `Resource` to be rendered by the UI (using ` bevy_inspector_egui::bevy_inspector::by_type_id::ui_for_resource`).  If it is possible to remove that limitation, then maybe we could insert the bevy events as is.

**Comment by rewin123** [comment]
It's possible

**Comment by rewin123** [comment]
https://github.com/rewin123/space_editor/blob/main/crates/editor_ui/src/inspector/mod.rs

Line 228

I'm from phone and can't write full example, by components reflection in inspector use undeps solution

**Comment by naomijub** [comment]
I just wanted the progress to not be lost and get documented. This is why I created this extra branch. However, the solution proposed can be applied to the other PR and probably solve the Default and Resource dependency. Will try it today

**Comment by rewin123** [comment]
And we can store events in single vector with 

```rust
struct UntypedEvent {
name : String, 
value: Box<dyn Reflect>, 
create_default: Box<dyn FnMut... >, 
show_ui: Box<dyn FnMut(&mut dyn Reflect) -> UiEvents> 
... 
}
```

**Comment by rewin123** [comment]
I'm not against merging this PR as a temporary solution, but ideally we should find a way to reduce the number of derives needed to only two - Event and Reflect (or just Event for just field less struct events like "struct NoFieldEvent;")

**Comment by ncomendant** [comment]
Honestly I think the `Default` dependency I added was never needed, since the event was stored as a Resource and being cloned anyway.

Looks like we're all on the same page. I'll open the PR again, but whatever you decide to do with it is fine by me.

**Comment by naomijub** [comment]
> I'm not against merging this PR as a temporary solution, but ideally we should find a way to reduce the number of derives needed to only two - Event and Reflect (or just Event for field less struct events like "struct NoFieldEvent;") 

Like I said, I didn't want progress to be lost, so I asked @ncomendant to open the PR on this branch. I loved your idea and will try it today in the other branch that I have open

**Comment by naomijub** [comment]
This PR was a documentation on the first solution to custom events UI. There is a new solution to be implemented which addresses the multiple derive dependencies

**Comment by rewin123** [comment]
@ncomendant I apologise that my comments caused the PR to be closed T_T But all manually wrapping way is too hard for support

**Comment by rewin123** [comment]
We can also store events in separate resources while getting rid of the Resource dependency. For example

``rust
#[derive(Resource) ]
struct ResourcrWrapper<T: Event>(pub T) ;
```

**Comment by rewin123** [comment]
I just realised that the PR was not about merging into main and was about saving the documentation and work done to pass on. I apologise, it turns out my comments were not for this PR, but for the events branch. Anyway, thanks for the very cool work already done

**Pull request closed without merging**
