### PR TITLE
Issue 63 - Add components window

### PR DESCRIPTION
**Pull request by naomijub**
On inspector right click, if there is an entity selected, an `Add Components` window will pop up:
 
image

There is an issue:
- [ ] if you leave the window in the gameview area, if moves the game camera.

### CODE REVIEW

**Comment by naomijub** [comment]
@rewin123 I think it feels great with this change, please feedback

**Comment by naomijub** [comment]
Tried to fix the camera movement when `Add components` is on top of game view the camera moves as well :( 
Any ideas?

**Comment by rewin123** [comment]
Try
```rust
world.resource_mut::<crate::editor::PanOrbitEnabled>().0 = false;
```
before 'update_pan_orbit' system

**Comment by rewin123** [comment]
I hope you don't oppose outside changes to the pull request, I've added a camera control fix and added an additional button to call the context window for adding a component. Now it is possible to call both by right mouse button and by clicking on "Add component" button.

**Comment by naomijub** [comment]
Awesome, no problem with collab PRs

**Pull request merged**
