### PR TITLE
Fix multiple selection

### PR DESCRIPTION
**Pull request by rewin123**
#204

### CODE REVIEW

**Comment by naomijub** [comment]
Will take a look after lunch

**Comment by rewin123** [comment]
> Will take a look after lunch

Thanks!

**Review by naomijub — APPROVED** [review]
Seems to be working, but there is a visual issue that annoys me, when you select holding shift, I can only see the main gizmos, I would include a wireframe on multi selected elements

**Comment by rewin123** [comment]
several lines running from the central gizmo to the centres of all selected objects?

**Comment by rewin123** [comment]
image

**Pull request merged**
