### PR TITLE
Fix camera vewport bug

### PR DESCRIPTION
**Pull request by rewin123**
#298

### CODE REVIEW

**Comment by naomijub** [comment]
Lint and fmt failed

**Comment by naomijub** [comment]
Tô have the lint fixed you should have rust latest, as the CI. Rustup update

**Comment by rewin123** [comment]
> To have the lint fixed you should have rust latest, as the CI. Rustup update

Yes, sure. I'm just hoping to wait for verification from whoever noticed the bug in the first place. As soon as I get confirmation that the bug has been fixed there too, I’ll fix clippy and upload it

**Comment by naomijub** [comment]
This doesnt work on MacOS

**Comment by naomijub** [comment]
Works on my side (improved the macos experience as well).
Don't forget to add documentation on git lfs:
```
### Dependencies
 - Git LFS for assets
 
git lfs install
git lfs pull
```

**Review by naomijub — APPROVED** [review]

**Pull request merged**
