### PR TITLE
Issue-80

### PR DESCRIPTION
**Pull request by naomijub**
- Reads Window Resize Event in PostUpdate, to update viewport.

Addresses https://github.com/rewin123/space_editor/issues/80

### CODE REVIEW

**Comment by rewin123** [comment]
Thanks for the pull request! 
I've tested the changes, but on my machine the error hasn't been fixed yet.

image

**Comment by naomijub** [comment]
Weird, it did fix on my end. Maybe move it to update?

**Comment by naomijub** [comment]
Well partial fix then 😂

**Comment by rewin123** [comment]
> Weird, it did fix on my end. Maybe move it to update?

Problem was in set_camera_viewport system. It was updating only when pointer in game tab. Fixed it

**Comment by naomijub** [comment]
> > Weird, it did fix on my end. Maybe move it to update?
> 
> 
> 
> Problem was in set_camera_viewport system. It was updating only when pointer in game tab. Fixed it

Wasn't pointer check supposed to  prevent game object rotation and translation when dealing with egui objects?

**Comment by rewin123** [comment]
Maybe. But the current method hasn't been used anywhere else except to block mosquito viewport updates

**Pull request merged**
